#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import ast

# ----------------------------
# Настройки путей
MANUAL_FILE = "LEXICON/RU/LEXICON_handlers_ru.py"
AUTO_FILE   = "handlers/LEXICON_RU.auto.py"
OUTPUT_FILE = "LEXICON/RU/LEXICON_handlers_final.py"

# ----------------------------

def parse_lexicon_dict(filepath: str, var_name: str = "LEXICON_HANDLERS_RU") -> dict:
    """Извлекает словарь из .py файла по имени переменной, используя ast (без exec!)."""
    if not os.path.exists(filepath):
        print(f"⚠️  Файл {filepath} не найден.")
        return {}

    with open(filepath, "r", encoding="utf-8") as f:
        try:
            tree = ast.parse(f.read())
        except SyntaxError as e:
            raise ValueError(f"Ошибка синтаксиса в {filepath}: {e}")

    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == var_name:
                    try:
                        return ast.literal_eval(node.value)
                    except Exception as e:
                        raise ValueError(f"Не удалось распарсить {var_name} в {filepath}: {e}")
    print(f"❌ Переменная {var_name} не найдена в {filepath}.")
    return {}


def merge_role_dicts(role: str, dict1: dict, dict2: dict):
    """Сливает два подсловаря одной роли с обнаружением конфликтов и дублей."""
    merged = {}
    all_keys = set(dict1.keys()) | set(dict2.keys())
    conflicts = []

    for key in all_keys:
        vals = []
        if key in dict1:
            vals.append(dict1[key])
        if key in dict2:
            vals.append(dict2[key])

        if len(vals) == 1:
            merged[key] = vals[0]
        else:
            # Есть дубль ключа — проверяем значения
            if vals[0] == vals[1]:
                # Одинаковые значения → оставляем один
                merged[key] = vals[0]
            else:
                # Разные значения → конфликт
                merged[f"{key}_conflict_1"] = vals[0]
                merged[f"{key}_conflict_2"] = vals[1]
                conflicts.append((key, vals[0], vals[1]))

    return merged, conflicts


def main():
    print("📥 Загружаем ручной словарь...")
    manual = parse_lexicon_dict(MANUAL_FILE, "LEXICON_HANDLERS_RU")

    print("📥 Загружаем авто-словарь...")
    auto = parse_lexicon_dict(AUTO_FILE, "LEXICON_RU")

    print("🔀 Объединяем словари...")
    final_lexicon = {}
    all_conflicts = []

    all_roles = set(manual.keys()) | set(auto.keys())
    for role in sorted(all_roles):
        d1 = manual.get(role, {})
        d2 = auto.get(role, {})
        merged_role, conflicts = merge_role_dicts(role, d1, d2)
        final_lexicon[role] = merged_role
        if conflicts:
            all_conflicts.append((role, conflicts))

    # Выводим конфликты
    if all_conflicts:
        print("\n❗ НАЙДЕНЫ КОНФЛИКТЫ (ключ с разными значениями):")
        for role, conflicts in all_conflicts:
            print(f"\n📁 Роль: {role}")
            for key, val1, val2 in conflicts:
                print(f"  🔑 Ключ: {key}")
                print(f"    → Значение 1: {repr(val1)[:100]}")
                print(f"    → Значение 2: {repr(val2)[:100]}")
    else:
        print("\n✅ Конфликтов не обнаружено.")

    # Сохраняем результат
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# FINAL MERGED LEXICON — manual + auto\n")
        f.write("# Generated by merge_handlers_lexicons.py\n\n")
        f.write("LEXICON_HANDLERS_RU = {\n")
        for role in sorted(final_lexicon):
            f.write(f'    "{role}": {{\n')
            role_dict = final_lexicon[role]
            for key in sorted(role_dict):
                value = role_dict[key]
                f.write(f'        "{key}": {repr(value)},\n')
            f.write("    },\n")
        f.write("}\n")

    print(f"\n💾 Результат сохранён в: {OUTPUT_FILE}")

    # Статистика
    total = sum(len(d) for d in final_lexicon.values())
    manual_total = sum(len(d) for d in manual.values())
    auto_total = sum(len(d) for d in auto.values())
    print(f"\n📊 Статистика:")
    print(f"   Ручные записи:       {manual_total}")
    print(f"   Авто-записи:         {auto_total}")
    print(f"   Итог (после merge):  {total}")
    if all_conflicts:
        print(f"   ⚠️  Конфликтов:       {sum(len(c) for _, c in all_conflicts)}")

    print("\n✅ Готово!")


if __name__ == "__main__":
    main()