LEXICON_HANDLERS_EN = {
    "admin": {
        "back_to_main_menu": "🏠 Back to Main Menu",
        "ban_button_not_a_number": "❌ The pressed button is not a number. Please report this to an administrator.",
        "ban_cancelled": "✅ Thanks! The ban was not applied.\nPlease try again.\nYou have exited the current process.",
        "ban_confirm_user_data": "👤 User to be banned:\nFirst Name: {first_name},\nLast Name: {last_name}, \nPhone: {tg_phone_number}\nUsername: {username}\n\nIs this correct?",
        "ban_enter_user_id_or_contact": "🔍 Please enter the Telegram ID of the user you want to ban,\nor forward their contact with the ID.",
        "choose_action": "⚙️ Choose an action:",
        "choose_ban_period_or_cancel": "⏱️ Select the ban duration.\nTo cancel the process, type /cancel",
        "choose_mailing_audience": "📢 Select the audience for the broadcast:",
        "choose_member_status_for_export": "📋 Select the member status to export the list for:",
        "confirm_new_registrator": "📝 User to be appointed as Registrator:\n{user_info}\n\nIs this correct?",
        "contact_has_no_id": "❌ Unfortunately, the contact does not contain an ID. Please send the Telegram ID directly.",
        "details_of_the_user_you_want_to_ban": "\n👤 Details of the user to be banned:\n\nFirst Name: {first_name},\nLast Name: {last_name}, \n\nPhone: {tg_phone_number}\n\nUsername: {username}\n\nIs this correct?\n        ",
        "enter_user_id_or_contact_for_mailing": "🔑 Enter the user's Telegram ID or forward their contact.",
        "error_completing_voting": "❌ An error occurred while completing the voting.",
        "error_deleting_variant": "❌ An error occurred while deleting the variant.",
        "error_during_registrator_assignment": "❌ An error occurred during registrator assignment: {ans_str}",
        "error_finishing_confirmation": "❌ An error occurred while finalizing voting results approval.",
        "error_intermediate_voting_results": "❌ An error occurred while calculating interim voting results.",
        "error_loading_registrators": "❌ An error occurred while loading the registrators list. Please try again.",
        "error_message": "⚠️ An error occurred: {err}",
        "error_promoting_to_super": "❌ An error occurred while appointing the Super-Registrator.",
        "error_removing_registrator": "❌ An error occurred while removing the Registrator.",
        "error_removing_superregistrator": "❌ An error occurred while removing the Super-Registrator.",
        "error_starting_voting": "❌ An error occurred while starting the voting.",
        "export_failed": "📤 Failed to export the members list.",
        "export_members_start": "📤 Export Members List",
        "failed_to_get_participant_id": "❌ Failed to retrieve the participant's ID.",
        "failed_to_get_user_id_for_ban": "❌ Failed to retrieve the user's ID.",
        "generic_error_try_again": "⚠️ An error occurred. Please try again.",
        "invalid_numeric_input": "🔢 Please enter a valid numeric value.",
        "main_menu": "🏠 Main Menu:",
        "message_has_no_text": "📝 The message contains no text. Please try again.",
        "message_too_long_max_4000": "📏 Message is too long (max. 4000 characters). Please try again.",
        "no_registrators": "📭 There are currently no Registrators.",
        "please_send_contact": "📲 Please forward the contact.",
        "process_new_registrator": "🔍 Please enter the Telegram ID of the user you want to assign a new status to,\nor forward their contact with the ID.",
        "process_registrator_contact_sent&no_contact": "❌ An error occurred. Please forward a valid contact.",
        "process_registrator_id_sent&no_member_id": "🔍 User not found.",
        "process_registrator_id_sent&no_text": "❌ An error occurred. Please send a valid ID.",
        "process_registrator_profile_not_found": "📂 User profile not found.",
        "registrator_added_success": "✅ Thanks! Registrator Candidate has been added!\nMessage sending result:\n{response}\nYou have exited the current process.",
        "registrator_card": "📝 Registrator: {username} {first_name} {last_name}",
        "registrator_invitation_message": "👋 Hello! The group administration has appointed you as a Registrator.\nThis means you will receive membership applications via the bot, which you can approve or ignore.\nIf you accept the Registrator role, tap the \"Accept\" button.\nIf you decline, tap the \"Decline\" button.",
        "registrator_not_added": "✅ Thanks! The Registrator was not added.\nPlease try again.\nYou have exited the current process.",
        "super_registrator_card": "⚡ Super-Registrator: {username} {first_name} {last_name}",
        "unexpected_error_finishing_confirmation": "⚠️ An unexpected error occurred while finalizing voting results approval.",
        "unknown_error": "❓ Unknown error.",
        "unknown_voting_status": "❓ Unknown voting status. Please contact the administration.",
        "use_buttons_or_cancel": "👆 Please use the buttons!\nTo cancel the registrator appointment, send the /cancel command.",
        "use_buttons_or_cancel_ban": "👆 Please use the buttons!\nTo cancel the ban process, send the /cancel command.",
        "user_banned_for_days": "🚫 User has been banned for {ban_time_days} days.",
        "user_not_found_in_group": "🔍 Such a participant was not found in the group.",
        "user_profile_not_found": "📂 Participant profile not found.",
        "voting_not_from_your_group": "❌ This voting does not belong to your group.",
    },

    "all_users": {
        "add_option": "📝 Add Variant",
        "admin_voting": "⚙️ Manage Voting",
        "admin_voting_1": "⚙️ Manage Voting",
        "admin_voting_2": "⚙️ Manage Voting",
        "all_valid_votes_in_group_value": "🗳️ Total valid votes in the group: {s_votist}\n⚙️ Choose next action:",
        "back": "⬅️ Back",
        "back_to_to_list_voting": "🔙 Back to Votings List",
        "back_to_to_list_voting_1": "🔙 Back to Votings List",
        "back_to_to_list_voting_2": "🔙 Back to Votings List",
        "back_to_to_list_voting_3": "🔙 Back to Votings List",
        "before": "➡️ Forward / Next",
        "choose_level_notification": "🔔 Select your notification level.\n\n📢 Max: Receive all updates about voting creation and progress.\n📌 Medium: Receive notifications about voting start and final stages only.\n🔕 Min: No voting updates from the bot.\n\n⚠️ Regardless of your level, you will always receive important messages from the administration and your Representative.",
        "choose_this_proxy": "🤝 Select this Representative",
        "enter_unique_name_or_username": "✏️ Enter a unique name or alias. It can be your real name or surname. It must be unique within this group so users can distinguish between Representatives. Ideally, keep it under 40 characters.",
        "error_empty_message_please_enter_username": "❌ Error: Empty message. Please enter an alias.",
        "f_description_proxy_info": "📝 Description:\n",
        "for_more_detailed_information_about_representative_info_pres": "\n📖 For more details about the Representative, tap the corresponding button.",
        "in_present_time_no_active_voting": "📭 There are currently no active votings.",
        "in_present_time_no_available_options": "📭 There are currently no available variants.",
        "in_present_time_no_completed_voting": "📭 There are currently no completed votings.",
        "in_present_time_no_voting_in_stage_addition_options": "📭 There are currently no votings in the variant submission phase.",
        "in_this_moment_no_available_representatives": "🤝 There are currently no available Representatives.",
        "incorrect_data": "❌ Invalid data.",
        "list_active_voting": "📋 Active Votings List:",
        "list_completed_voting": "📋 Completed Votings List:",
        "list_future_voting": "📋 Upcoming Votings List:",
        "list_options_to_golosovaniyu": "📝 Variants List for Voting:\n",
        "list_representatives": "<b>🤝 Representatives List:</b>\n\n",
        "list_representatives_1": "📋 Representatives List",
        "main_menu": "🏠 Main Menu",
        "main_menu_1": "🏠 Main Menu",
        "occurred_error_data_not_found": "❌ An error occurred. Data not found.",
        "occurred_error_data_not_found_1": "❌ An error occurred. Data not found.",
        "occurred_error_message_not_found": "❌ An error occurred. Message not found.",
        "occurred_error_please_try_again": "⚠️ An error occurred. Please try again.",
        "occurred_error_with_loading_list_representatives": "❌ An error occurred while loading the Representatives list.",
        "occurred_error_with_loading_list_voting": "❌ An error occurred while loading the Votings list.",
        "occurred_error_with_saving_level_notification_try_later": "❌ An error occurred while saving your notification level. Please try again later.",
        "occurred_error_with_view_options_voting": "❌ An error occurred while viewing voting variants.",
        "please_confirm_correct_is_entered_yours_name_username_value": "✅ Please confirm if your name/alias is entered correctly:\n\n    {message_text}",
        "please_use_buttons": "👆 Please use the buttons!\n\nIf you wish to cancel the status change, tap a button or send /cancel.",
        "please_use_buttons_above": "👆 Please use the buttons above!\n\nIf you wish to cancel the process, tap the button below this message or send /cancel.",
        "return_in_main_menu": "🏠 Return to Main Menu",
        "return_in_main_menu_1": "🏠 Return to Main Menu",
        "return_in_main_menu_2": "🏠 Return to Main Menu",
        "section_about_about_yourself_changed": "✅ 'About Me' section has been updated!",
        "such_name_username_already_exists_try_invent_another_u": "⚠️ This name/alias already exists. Please choose a different alias or add something unique to distinguish yourself.",
        "thank_you_username_not_changed_try_also_time_or_press_button": "✅ Thanks! Alias was not changed.\nPlease try again, or tap a button to cancel the process.",
        "write_what_would_you_want_tell_about_about_yourself_drugim_u": "✍️ Write what you'd like to tell other group members about yourself.\n🤝 If you become a Representative, potential followers will be able to read this section.\nIf you wish to cancel, tap a button or type /cancel.",
        "you_chosen_unknown_level": "❓ You selected: Unknown Level",
        "you_chosen_value": "✅ You selected: {level_note}",
        "your_username_changed": "✅ Your alias has been updated!",
    },

    "ban": {
        "user_banned_for_days": '🚫 You are banned in this group until: "{ban_expiration}".\n\nYou can still vote and delegate your voice.\n\nIf you disagree with this ban, please contact an administrator.',
    },

    "candidate": {
        "auth_success_you_member_group": '✅ Authorization successful! You are now a group member.',
        "back": '⬅️ Back',
        "back_1": '⬅️ Back',
        "before": '➡️ Next',
        "before_1": '➡️ Next',
        "choose_interesting_info": '📚 Select the information you\'d like to view:',
        "description": '\n📝 Description: ',
        "enter_unique_token_if_he_to_you_exists": '🔑 Enter your unique token (if you have one).\n',
        "error_in_data": '❌ Error in data.',
        "error_no_messages_for_edit": '❌ Error: No message available to edit.',
        "error_with_notification_super_registrator": '❌ Error notifying Super-Registrator: {result}',
        "error_with_notification_super_registrator_value": '❌ Error notifying Super-Registrator: {result}',
        "for_detailed_information_press_to_one_from_buttons_below": '\n\n📖 For more details, tap one of the buttons below:',
        "good_welcome_you_passed_by_special_link_this_bot_for_provede": '🎉 Welcome! You\'ve joined via a special link.\nThis bot is designed for conducting votings.\nPlease complete your registration to start using the bot.\nOnce registered, you\'ll gain voting rights and the ability to participate.\nFor more information, tap the "Information" button.',
        "here_should_was_be_info_about_bote": 'ℹ️ Information about the bot should appear here.',
        "here_should_was_be_theory_about_newdem": '📚 Theory about NewDem should appear here.',
        "in_this_moment_no_available_representatives": '🤝 There are currently no available Representatives.',
        "incorrect_data": '❌ Invalid data.',
        "list_representatives_username_number_votes": '📋 Representatives List:\n(Alias, Number of Votes)',
        "list_representatives_username_number_votes_1": '📋 Representatives List:\n(Alias, Number of Votes)',
        "main_menu": '🏠 Main Menu',
        "main_menu_1": '🏠 Main Menu',
        "not_found_info_about_representative_info": '🔍 Representative information not found.',
        "not_found_profile_user": '🔍 User profile not found.',
        "not_success_determine_group": '❌ Failed to determine the group.',
        "not_success_edit_message": '❌ Failed to edit the message.',
        "number_trusted_votes": '👤 Alias: {username}\n📝 Description: {description}\n🗳️ Trusted Votes: {trusted_votes}',
        "occurred_error": '⚠️ An error occurred: {err}',
        "occurred_error_please_try_again": '⚠️ An error occurred. Please try again.',
        "occurred_error_please_try_again_1": '⚠️ An error occurred. Please try again.',
        "occurred_error_with_getting_information_about_representative": '❌ An error occurred while retrieving Representative information.',
        "occurred_error_with_loading_list_representatives": '❌ An error occurred while loading the Representatives list.',
        "occurred_error_with_loading_list_voting": '❌ An error occurred while loading the Votings list.',
        "occurred_error_with_loading_main_menu": '❌ An error occurred while loading the Main Menu.',
        "please_use_buttons_if_you_want_cancel_change_status_send_com": '👆 Please use the buttons!\n\nIf you wish to cancel the status change, send the /cancel command.',
        "prevysheno_quantity_attempts_input_token": '🔒 Maximum token input attempts exceeded.',
        "to_chto_you_entered_not_seems_to_token_try_again_or_type_can": '❌ What you entered doesn\'t look like a valid token. Please try again or type /cancel.',
        "token_invalid_try_again_or_continue_questionnaire": '❌ Invalid token. Please try again or continue with the registration form.',
        "token_not_can_be_empty_try_eshch_time": '❌ Token cannot be empty. Please try again:',
        "token_not_valid_try_again_or_continue_questionnaire": '❌ Token is not valid. Please try again or continue with the registration form.',
        "you_consisting_in_group": '✅ You have remained in the group.',
        "you_exited_from_group": '👋 You have left the group!',
        "you_exited_from_machines_consisting_and_return_in_main_menu": '✅ You have exited the current process and returned to the Main Menu.',
        "you_exited_in_main_menu": '🏠 You have returned to the Main Menu.',
        "you_not_registered_in_group_proceed_registration": '⚠️ You are not registered in this group. Please complete your registration.',
        "you_returned_in_main_menu": '🏠 You have been returned to the Main Menu.',
        "you_valid_want_exit_from_group_vs_correct": '❓ Are you sure you want to leave the group?\nIs this correct?',
        "your_status_in_group": '\n🏷️ Your status in the group:',
    },
    "delegate": {
        "error_value": "❌ Error: {comment}",
        "error_value_1": "❌ Error: {comment}",
        "occurred_error_please_try_again": "⚠️ An error occurred. Please try again.",
        "occurred_error_value": "⚠️ An error occurred: {err}",
        "occurred_error_value_1": "⚠️ An error occurred: {err}",
        "option_not_created_want_is_add_another_option": "❌ Variant not created! Would you like to add another variant?",
        "please_confirm_correct_is_entered_title_and_description_opti": "✅ Please confirm if the variant title and description are entered correctly:\n\nTitle: {title}\nDescription: {description}",
        "please_confirm_correct_is_entered_title_and_description_voti": "✅ Please confirm if the voting title and description are entered correctly:\n\nTitle: {title}\nDescription: {description}",
        "please_enter_description_option": "📝 Please enter the variant description.",
        "please_enter_description_voting": "📝 Please enter the voting description.",
        "please_enter_title_option": "📝 Please enter the variant title.",
        "please_enter_title_option_1": "📝 Please enter the variant title.",
        "please_enter_title_voting": "📝 Please enter the voting title.",
        "please_enter_title_voting_1": "📝 Please enter the voting title.",
        "thank_you_all_options_added_you_exited_from_machines_consist": "✅ Thank you! All variants have been added! You have exited the current process.",
        "thank_you_option_created_nkhotite_is_add_eshch_option": "✅ Thank you! Variant created!\nWould you like to add another variant?",
        "thank_you_voting_created_you_exited_from_machines_consisting": "✅ Thank you! Voting created! You have exited the current process.",
        "title_not_must_be_longer_40_characters_try_again": "⚠️ Title must not exceed 40 characters. Please try again.",
        "title_not_must_be_longer_40_characters_try_again_1": "⚠️ Title must not exceed 40 characters. Please try again.",
        "voting_not_created_try_also_time_you_exited_from_machines_co": "❌ Voting not created! Please try again. You have exited the current process.",
    },

    "frozen": {
        "auth_success_you_member_group": "✅ Authorization successful! You are now a group member.",
        "enter_a_unique_token": "🔑 Enter your unique token (if you have one).\n",
        "error_notify_super_registrator": "❌ Error notifying Super-Registrator: {result}",
        "error_with_notification_super_registrator": "❌ Error notifying Super-Registrator: ",
        "not_found_profile_user": "🔍 User profile not found.",
        "number_token_entry_attempts_exceeded": "🔒 Maximum token entry attempts exceeded.",
        "to_chto_you_entered_not_seems_to_token_try_again_or_type_can": "❌ What you entered doesn't look like a valid token. Please try again or type /cancel.",
        "to_you_no_confirming_token_or_expired_period_his_actions_pop": "❌ You don't have a confirmation token or it has expired.\nPlease request a new token from the administration.",
        "to_you_no_confirming_token_or_expired_period_his_actions_pop_1": "❌ You don't have a confirmation token or it has expired.\nPlease request a new token from the administration.",
        "token cannot be empty": "❌ Token cannot be empty. Please try again:",
        "token_invalid_try_again_or_continue_questionnaire": "❌ Invalid token. Please try again or continue with the registration form.",
        "token_not_valid_try_again_or_continue_questionnaire": "❌ Token is not valid. Please try again or continue with the registration form.",
        "you_don't_have_verification_token": "❌ You don't have a verification token or it has expired.\nPlease request a new token from the administration.",
        "you_not_registered_in_group_proydite_registratsiyu": "⚠️ You are not registered in this group. Please complete your registration.",
    },

    "last": {
        "you_pressed_button_value_n": '🔘 You pressed the button: "{butt_data}".\nIt was not processed. If you need help, use the /help command.',
        "you_written_value_n": '✍️ You wrote: "{text}".\nYour message was not processed. If you need help, use the /help command.',
    },

    "member": {
        "back": "⬅️ Back",
        "back_1": "⬅️ Back",
        "before": "➡️ Next",
        "before_1": "➡️ Next",
        "choose_proxy_kotoromu_you_trust_your_vote": "🤝 Select a Representative to delegate your vote to:",
        "detailed_info": "📖 Detailed Information",
        "detailed_info_1": "📖 Detailed Information",
        "enter_unique_name_or_username": "✏️ Enter a unique name or alias. This can be your real name (or surname). It must be unique within this group so users can distinguish between Representatives. Ideally, keep it under 40 characters.",
        "enter_unique_name_or_username_1": "✏️ Enter a unique name or alias.\nThis can be your real name (or surname).\nIt must be unique within this group,\nso users can distinguish between Representatives.\nIdeally, keep it under 40 characters.",
        "enter_unique_name_or_username_2": "✏️ Enter a unique name or alias. This can be your real name (or surname). It must be unique within this group so users can distinguish between Representatives. Ideally, keep it under 40 characters.",
        "enter_username": "✏️ Please enter an alias.",
        "enter_username_1": "✏️ Please enter an alias.",
        "error_in_data": "❌ Error in data.",
        "error_user_not_found": "❌ Error: User not found",
        "error_with_voting_value": "❌ Voting error: {message}",
        "in_this_moment_no_available_representatives": "🤝 There are currently no available Representatives.",
        "in_this_moment_no_available_representatives_1": "🤝 There are currently no available Representatives.",
        "incorrect_data": "❌ Invalid data.",
        "main_menu": "🏠 Main Menu",
        "main_menu_1": "🏠 Main Menu",
        "not_found_info_about_representative_info": "🔍 Representative information not found.",
        "not_found_profile_user": "🔍 User profile not found.",
        "occurred_error_please_try_again": "⚠️ An error occurred. Please try again.",
        "occurred_error_please_try_again_1": "⚠️ An error occurred. Please try again.",
        "occurred_error_please_try_again_2": "⚠️ An error occurred. Please try again.",
        "occurred_error_please_try_again_3": "⚠️ An error occurred. Please try again.",
        "occurred_error_try_later": "⚠️ An error occurred. Please try again later.",
        "occurred_error_try_later_1": "⚠️ An error occurred. Please try again later.",
        "occurred_error_value": "⚠️ An error occurred: {err}",
        "occurred_error_value_1": "⚠️ An error occurred: {err}",
        "occurred_error_with_assignment_status_proxy": "❌ An error occurred while assigning the Representative status.",
        "occurred_error_with_assignment_status_proxy_1": "❌ An error occurred while assigning the Representative status.",
        "occurred_error_with_assignment_status_proxy_2": "❌ An error occurred while assigning the Representative status.",
        "occurred_error_with_assignment_status_registrator": "❌ An error occurred while assigning the Registrator status.",
        "occurred_error_with_choice_deputy": "❌ An error occurred while selecting an Alternate.",
        "occurred_error_with_deletion_status_admin": "❌ An error occurred while removing the Administrator status.",
        "occurred_error_with_deletion_status_proxy": "❌ An error occurred while removing the Representative status.",
        "occurred_error_with_getting_information_about_representative": "❌ An error occurred while retrieving Representative information.",
        "occurred_error_with_loading_list_representatives": "❌ An error occurred while loading the Representatives list.",
        "occurred_error_with_loading_list_representatives_1": "❌ An error occurred while loading the Representatives list.",
        "occurred_error_with_trust_votes": "❌ An error occurred while delegating your vote.",
        "occurred_error_with_voting": "❌ An error occurred during voting.",
        "offer_become_registrator_intended_not_you": "⚠️ This Registrator invitation was not intended for you.",
        "offer_become_registrator_intended_not_you_1": "⚠️ This Registrator invitation was not intended for you.",
        "please_confirm_correct_is_entered_yours_name_username_value": "✅ Please confirm if your name/alias is entered correctly:\n\n{username}",
        "please_confirm_correct_is_entered_yours_name_username_value_1": "✅ Please confirm if your name/alias is entered correctly:\n\n{username}",
        "please_enter_telegram_id_member_whose_you_want_to_do_yours_z": "🔍 Please enter the Telegram ID of the member\n\n    you want to appoint as your Alternate, or forward their contact with the ID.",
        "please_use_buttons": "👆 Please use the buttons!\n\nIf you wish to cancel the status change, send the /cancel command.",
        "please_use_buttons_1": "👆 Please use the buttons!\n\nIf you wish to cancel the process, send the /cancel command.",
        "such_name_username_already_exists_try_invent_another_usernam": "⚠️ This name/alias already exists. Please choose a different alias or add something unique to distinguish yourself.",
        "such_name_username_already_exists_try_invent_another_usernam_1": "⚠️ This name/alias already exists. Please choose a different alias or add something unique to distinguish yourself.",
        "thank_you_username_not_added_try_also_time_or_press_button_f": "✅ Thank you! Alias was not added.\nPlease try again, or tap a button to cancel the process.",
        "thank_you_username_not_added_try_enter_username_also_time_or": "✅ Thank you! Alias was not added.\nPlease try entering the alias again, or tap a button to cancel the process.",
        "unknown_error_with_assignment_deputy": "❓ Unknown error while appointing an Alternate.",
        "unknown_user": "👤 Unknown user",
        "unknown_user_1": "👤 Unknown user",
        "username_value_description_value_number_trusted_votes_value": "👤 Alias: {username}\n📝 Description: {description}\n🗳️ Trusted Votes: {trusted_votes}",
        "value_use_buttons_under_last_soobshcheniem_for_dalьneyshikh_": "{message}\n\n👆 Use the buttons below the last message to proceed.",
        "you_already_are_proxy": "✅ You are already a Representative.",
        "you_already_are_registrator": "✅ You are already a Registrator.",
        "you_already_are_registrator_1": "✅ You are already a Registrator.",
        "you_became_proxy": "🎉 You are now a Representative!",
        "you_became_proxy_1": "🎉 You are now a Representative!",
        "you_became_registrator": "🎉 You are now a Registrator!",
        "you_became_registrator_1": "🎉 You are now a Registrator!",
        "you_became_registrator_2": "🎉 You are now a Registrator!",
        "you_must_choose_about_yourself_proxy_to_have_right_vote": "\n⚠️ You must select a Representative to have voting rights.",
        "you_not_are_candidate_in_registrators": "⚠️ You are not a Registrator candidate.",
        "you_not_are_candidate_in_registrators_1": "⚠️ You are not a Registrator candidate.",
        "you_not_are_candidate_in_registrators_2": "⚠️ You are not a Registrator candidate.",
        "you_not_are_member_group": "⚠️ You are not a group member.",
        "you_not_are_member_group_1": "⚠️ You are not a group member.",
        "you_not_are_member_group_2": "⚠️ You are not a group member.",
        "you_not_are_member_group_3": "⚠️ You are not a group member.",
        "you_not_are_member_group_4": "⚠️ You are not a group member.",
        "you_not_are_member_group_5": "⚠️ You are not a group member.",
        "you_not_became_registrator": "❌ You have not become a Registrator!",
        "you_resigned_ot_role_admin": "🚪 You have resigned as Administrator!",
        "you_resigned_ot_role_registrator": "🚪 You have resigned as Registrator!",
        "you_stopped_be_proxy": "🚪 You are no longer a Representative!",
    },

    "owner": {
        "choose_which_status_you_want_add_user_or_remove_if_want_canc": "👤 Select which status you want to add to or remove from the user.\n\n⚠️ To cancel the process, type /cancel",
        "conditions_not_can_be_empty_try_again": "⚠️ Conditions cannot be empty. Please try again.",
        "conditions_not_can_be_empty_try_again_1": "⚠️ Conditions cannot be empty. Please try again.",
        "conditions_participation_success_changed": "✅ Participation conditions have been successfully updated.",
        "confirm_duration_stages_voting_in_days": "⏱️ Confirm the duration of voting stages (in days):\n1. Variant Submission: {duration_add_variants} days\n2. Main Stage: {duration_first_stage} days\n3. Final Stage: {duration_final} days\n4. Results Confirmation: {duration_confirmation} days\n\nIs this correct?",
        "confirm_thresholds_trusted_votes": "📊 Confirm the trusted vote thresholds:\n1. Minimum number of votes: {threshold_in_voices}\n2. Minimum percentage of total votes: {threshold_in_percent}\n\nIs this correct?",
        "data_member_not_found": "🔍 Member data not found.",
        "data_member_not_found_1": "🔍 Member data not found.",
        "data_member_to_whom_you_change_status_name_value_last_name_v": "👤 Member whose status you are changing:\nName: {first_name},\n\nSurname: {last_name}, \nPhone: {tg_phone_number}\n\nAlias: {username}\n\nIs this correct?",
        "data_member_to_whom_you_change_status_name_value_last_name_v_1": "👤 Member whose status you are changing:\nName: {first_name},\n\nSurname: {last_name}, \nPhone: {tg_phone_number}\n\nAlias: {username}\n\nIs this correct?",
        "data_member_to_whom_you_change_status_name_value_last_name_v_2": "👤 Member whose status you are changing:\nName: {first_name},\n\nSurname: {last_name}, \nPhone: {tg_phone_number}\n\nAlias: {username}\n\nIs this correct?",
        "description_group_success_changed": "✅ Group description has been successfully updated.",
        "description_not_can_be_empty_try_again": "⚠️ Description cannot be empty. Please try again.",
        "description_not_can_be_empty_try_again_1": "⚠️ Description cannot be empty. Please try again.",
        "enter_duration_stages_voting_in_days_in_next_formate": "⏱️ Enter the duration of voting stages (in days) in the following format:\n1. Variant Submission stage\n2. Main stage\n3. Final stage\n4. Results Confirmation stage\nExample: `2 3 1 1` (separated by spaces).",
        "enter_duration_stages_voting_in_days_in_next_formate_1": "⏱️ Enter the duration of voting stages (in days) in the following format:\n",
        "enter_id_or_link_to_channel_chat_for_deletion_from_mailing": "🔗 Enter the ID or link of the channel/chat to remove from broadcasts:",
        "enter_id_or_link_to_channel_chat_for_mailing": "📢 Enter the ID or link of the channel/chat for broadcasts:",
        "enter_id_or_link_to_main_channel_chat": "🎯 Enter the ID or link of the main channel/chat:",
        "enter_new_conditions_participation_in_group": "📝 Enter the new group participation conditions:",
        "enter_new_description_group": "✏️ Enter the new group description:",
        "enter_new_name_group": "✏️ Enter the new group name:",
        "enter_thresholds_trusted_votes_in_next_formate": "📊 Enter the trusted vote thresholds in the following format:\n1. Minimum number of votes (integer or decimal)\n2. Minimum percentage of total votes (integer or decimal)\nExamples:\n- `10.5 5`\n- `10,5 1,5`\n- `10 15`\n(Separated by spaces).",
        "enter_value_thresholds_through_space": "🔢 Enter the threshold values separated by a space.",
        "id_or_link_not_can_be_empty_try_again": "⚠️ ID or link cannot be empty. Please try again.",
        "id_or_link_not_can_be_empty_try_again_1": "⚠️ ID or link cannot be empty. Please try again.",
        "id_or_link_not_can_be_empty_try_again_2": "⚠️ ID or link cannot be empty. Please try again.",
        "id_or_link_not_can_be_empty_try_again_3": "⚠️ ID or link cannot be empty. Please try again.",
        "id_or_link_not_can_be_empty_try_again_4": "⚠️ ID or link cannot be empty. Please try again.",
        "id_or_link_not_can_be_empty_try_again_5": "⚠️ ID or link cannot be empty. Please try again.",
        "invalid_input_value": "❌ Invalid input: {e}\nPlease enter two numbers separated by a space.\nYou can use a dot or comma as the decimal separator.",
        "invalid_input_value_please_enter_four_positive_number_throug": "❌ Invalid input: {e}\nPlease enter four positive numbers separated by a space.",
        "message_not_contains_text_please_try_again": "📝 The message contains no text. Please try again.",
        "name_group_success_changed_to_value": "✅ Group name has been successfully changed to: {new_name}",
        "name_not_can_be_empty_try_again": "⚠️ Name cannot be empty. Please try again.",
        "name_not_can_be_empty_try_again_1": "⚠️ Name cannot be empty. Please try again.",
        "occurred_error_data_incorrect_must_be_4_positive_number": "❌ Error: Invalid data. Please enter exactly 4 positive numbers.",
        "occurred_error_data_not_found": "❌ Error: Data not found.",
        "occurred_error_value": "⚠️ An error occurred: {err}",
        "occurred_error_value_1": "⚠️ An error occurred: {err}",
        "occurred_error_value_2": "⚠️ An error occurred: {err}",
        "occurred_error_value_3": "⚠️ An error occurred: {err}",
        "occurred_error_value_4": "⚠️ An error occurred: {ans_str}",
        "occurred_error_value_5": "⚠️ An error occurred: {err}",
        "occurred_error_with_changes_conditions_participation": "❌ An error occurred while updating participation conditions.",
        "occurred_error_with_changes_description_group": "❌ An error occurred while updating the group description.",
        "occurred_error_with_changes_name_group": "❌ An error occurred while updating the group name.",
        "occurred_error_with_processing_request": "❌ An error occurred while processing your request.",
        "please_enter_correct_numeric_value": "🔢 Please enter a valid numeric value.",
        "please_enter_telegram_id_member_to_whom_you_want_grant_new_s": "🔍 Please enter the Telegram ID of the member\n\nwhose status you want to change, or forward their contact with the ID.",
        "please_enter_telegram_id_member_to_whom_you_want_grant_new_s_1": "🔍 Please enter the Telegram ID of the member\n\nwhose status you want to change, or forward their contact with the ID.",
        "please_send_contact": "📲 Please forward the contact.",
        "please_use_buttons": "👆 Please use the buttons!\n\nTo cancel the registrator assignment, send the /cancel command.",
        "please_use_buttons_1": "👆 Please use the buttons!\n\nTo cancel the status change, send the /cancel command.",
        "setting_prodolzhitelьnosti_stages_cancelled": "⏹️ Stage duration setup has been cancelled.",
        "setting_thresholds_trusted_votes_cancelled": "⏹️ Trusted vote threshold setup has been cancelled.",
        "sorry_such_status_no_try_again": "⚠️ Sorry, such a status does not exist.\n\nPlease try again.\nYou have exited the current process.",
        "such_member_not_found": "🔍 Such a member was not found.",
        "such_member_not_found_1": "🔍 Such a member was not found.",
        "thank_you_new_status_not_added_try_also_time_you_exited_from": "✅ Thanks! The new status was not added.\nPlease try again.\nYou have exited the current process.",
        "thank_you_new_status_not_added_try_also_time_you_exited_from_1": "✅ Thanks! The new status was not added.\nPlease try again.\nYou have exited the current process.",
        "thank_you_status_member_updated": "✅ Thanks! Member status has been updated!\n\nYou have exited the current process.",
        "to_sorry_id_contact_missing_try_send_simply_id": "❌ Unfortunately, the contact does not contain an ID. Please send the Telegram ID directly.",
        "you_exited_from_machines_consisting": "✅ You have exited the current process.",
    },

    "proxy": {
        "enter_text_rassylki": "📝 Enter broadcast message text:",
        "message_slishkom_dlinnoe_maks_4000_characters_try_again": "📏 Message is too long (max. 4000 characters). Please try again.",
        "text_not_can_be_empty_try_eshch_time": "⚠️ Text cannot be empty. Please try again:",
    },

    "reg_process": {
        "auth_success_you_member_group": "✅ Authorization successful! You are now a group member.",
        "enter_text": "✍️ Please enter the text.",
        "enter_unique_token_if_he_to_you_exists": "🔑 Enter your unique token (if you have one).\nIf not, please answer the administration's questions.\n\n",
        "error_not_found_info_about_group": "❌ Error: Group information not found.",
        "error_with_notification_registrator_value": "❌ Error notifying Registrator: {result}",
        "error_with_notification_super_registrator_value": "❌ Error notifying Super-Registrator: {result}",
        "exceeded_quantity_attempts_input_token": "🔒 Maximum token entry attempts exceeded.",
        "nobody_from_registratorov_not_know": "🤷 I don't know any of the Registrators",
        "occurred_error_value": "⚠️ An error occurred: {err}",
        "thank_you_choose_registrator": "✅ Thank you!\nSelect a Registrator you know\nso they can verify your identity.\nIf you don't know anyone, tap 'I don't know anyone'",
        "thank_you_yours_data_saved": "✅ Thank you! Your data has been saved.\nThe administration will review it and grant you the appropriate rights.\nYou have exited the current process.",
        "token_invalid_try_again_or_continue_questionnaire": "❌ Invalid token. Please try again or continue with the registration form.",
        "token_not_valid_try_again_or_continue_questionnaire": "❌ Token is not valid. Please try again or continue with the registration form.",
        "write_about_about_yourself": "✍️ Tell us about yourself",
        "you_already_registered_in_group": "✅ You are already registered in this group.",
    },

    "registrator": {
        "comment_not_can_be_empty_try_once_more_time": "⚠️ Comment cannot be empty. Please try again:",
        "comment_not_can_be_empty_try_once_more_time_1": "⚠️ Comment cannot be empty. Please try again:",
        "congratulate_your_application_to_join_in_group_approved_or_y": "🎉 Congratulations! Your application to join the group has been approved (or your membership rights have been restored). You are now a full-fledged member and can participate in votings.\n\n⚠️ Please note: For your vote to be counted, you must either select a Representative or become one yourself.\nChoosing a Representative does not prevent you from voting personally in any voting.\nHowever, if you do not vote, your Representative's vote will be counted on your behalf.\nIf you are dissatisfied with how your Representative votes, you can change them at any time or become a Representative yourself.\nThe Representative status comes with obligations, such as participating in all votings.\nA Representative can appoint an Alternate to vote on their behalf in case of absence.\nThe Representative is fully responsible for their Alternate's votes, just as for their own.",
        "enter_comment_for_token": "📝 Enter a comment for the token:",
        "error_with_binding_token_to_user_value": "❌ Error binding token to user: {msg}",
        "internal_error_try_later": "⚠️ Internal error. Please try again later.",
        "message_unavailable": "🔒 Message is unavailable.",
        "not_success_finish_registration": "❌ Failed to complete registration.",
        "not_success_get_id_user_please_try_once_more_time": "❌ Failed to retrieve user ID. Please try again.",
        "occurred_error_with_confirmation_membership": "❌ An error occurred while confirming membership.",
        "occurred_error_with_rejection_membership": "❌ An error occurred while rejecting membership.",
        "received_inaccessiblemessage": "📥 Received InaccessibleMessage",
        "thank_you_user_value_not_received_status_member": "✅ Thank you! User {tg_id} has not been granted 'Member' status.",
        "thank_you_user_value_received_status_member": "✅ Thank you! User {tg_id} has been granted 'Member' status.",
        "user_with_id_value_not_found": "🔍 User with ID {tg_id} not found.",
        "user_with_id_value_not_found_1": "🔍 User with ID {tg_id} not found.",
    },

    "short_reg_process": {
        "error_not_found_info_about_group": "❌ Error: Group information not found.",
        "error_with_notification_registrator_value": "❌ Error notifying Registrator: {result}",
        "error_with_notification_super_registrator_value": "❌ Error notifying Super-Registrator: {result}",
        "message_unavailable": "🔒 Message is unavailable.",
        "nobody_from_registrators_not_know": "🤷 I don't know any of the Registrators",
        "occurred_error_value": "⚠️ An error occurred: {err}",
        "occurred_error_with_start_process_registration": "❌ An error occurred while starting the registration process.",
        "please_use_buttons_with_choice_moderator_if_you_want_cancel_": "👆 Please use the buttons when selecting a Moderator.\n\nIf you wish to cancel the registration form, send the /cancel command.",
        "thank_you_choose_registrator_whose_know_to_he_could_confirm_": "✅ Thank you!\nSelect a Registrator you know\nso they can verify your identity.\nIf you don't know anyone,\ntap the 'I don't know anyone' button.",
        "thank_you_yours_data_saved_admin_team_them_confirm_and_given": "✅ Thank you! Your data has been saved.\nThe administration will review it and grant you the appropriate rights.\nYou have exited the current process.",
        "write_about_about_yourself": "✍️ Tell us about yourself",
        "you_already_registered_in_group": "✅ You are already registered in this group.",
    },

    "token": {
        "comment_not_can_be_empty_try_once_more_time": "⚠️ Comment cannot be empty. Please try again:",
        "comment_not_can_be_empty_try_once_more_time_1": "⚠️ Comment cannot be empty. Please try again:",
        "comment_not_can_be_empty_try_once_more_time_2": "⚠️ Comment cannot be empty. Please try again:",
        "comment_not_can_be_empty_try_once_more_time_3": "⚠️ Comment cannot be empty. Please try again:",
        "comment_not_can_be_empty_try_once_more_time_4": "⚠️ Comment cannot be empty. Please try again:",
        "comment_not_can_be_empty_try_once_more_time_5": "⚠️ Comment cannot be empty. Please try again:",

        "created_tokeny_lot_value_value": "🎫 Tokens created for Lot #",
        "enter_comment_for_these_tokens": "📝 Enter a comment for these tokens:",
        "enter_comment_for_these_tokens_1": "📝 Enter a comment for these tokens:",
        "enter_comment_for_this_token": "📝 Enter a comment for this token:",

        "enter_correct_number": "🔢 Please enter a valid number.",
        "enter_correct_number_1": "🔢 Please enter a valid number.",
        "enter_correct_token": "🔑 Please enter a valid token.",
        "enter_correct_token_1": "🔑 Please enter a valid token.",

        "enter_number_existing_lot_or_press_button_below_if_lot_new": "🔢 Enter the number of an existing lot, or tap the button below if creating a new lot:",
        "enter_token_for_mark_kak_obsolete": "🔑 Enter the token to mark as obsolete:",
        "export_tokens": "📤 Export Tokens",

        "how_much_tokens_create": "🔢 How many tokens to create?",
        "how_much_tokens_create_1": "🔢 How many tokens to create?",
        "how_much_tokens_issue": "📦 How many tokens to issue?",

        "issued_token_value": "✅ Token issued:\n\n<code>{tokens_list}</code>",
        "issued_tokeny_value": "✅ Tokens issued:\n{tokens_list}",

        "menu_management_tokens": "🔑 Token Management Menu:",
        "menu_management_tokens_1": "🔑 Token Management Menu:",
        "menu_management_tokens_2": "🔑 Token Management Menu:",
        "menu_management_tokens_3": "🔑 Token Management Menu:",

        "not_specified_quantity_tokens": "❌ Token quantity not specified.",
        "not_success_create_lot_tokens": "❌ Failed to create token lot.",
        "not_success_export_tokeny": "❌ Failed to export tokens.",
        "not_success_issue_tokeny": "❌ Failed to issue tokens.",
        "not_success_issue_tokeny_1": "❌ Failed to issue tokens.",
        "not_success_update_status_token": "❌ Failed to update token status.",

        "number_lot_must_be_chislom_try_once_more_time": "🔢 Lot number must be a numeric value. Please try again:",
        "return_in_main_menu": "🏠 Return to Main Menu:",
        "skip_avtomaticheskiy_number": "⏭️ Skip (auto-generate number)",
        "token_not_found_or_already_expired": "🔍 Token not found or already expired.",
        "token_success_marked_kak_obsolete": "✅ Token successfully marked as obsolete.",
    },
}